name: Deploy                 

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
   deploy:
    runs-on: ubuntu-latest
    env:
        AZURE_WEBAPP_NAME: webappdeploy    
        AZURE_WEBAPP_PACKAGE_PATH: '.'     
        DOTNET_VERSION: '3.1.x'    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
