name: Deploy
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Download artifact from Github
      run: |
        echo "Version is: ${{ github.event.inputs.version }}" 
        wget https://maven.pkg.github.com/2115-27/dotnetcore-hello-world/Helloworld/${{needs.Pre-Release.outputs.currentversion}}/Helloworld.${{needs.Pre-Release.outputs.currentversion}}.nupkg

          
        
