name: Deploy

env:
  AZURE_WEBAPP_NAME: webappdeploy   # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5'                 # set this to the .NET Core version to use

on:
  workflow_dispatch:
    inputs: 
       version:
          description: 'Version'
          default: '22.2.66'
          required: true
          type: string
       Environment:
          type: choice
          description: environment
          options:
          - DEV
          - TEST
          - STG
          - PROD
          required: true
    

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
        
