name: Deploy
on:
  workflow_call:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Download artifact from Github
      run: |
        echo "Version is: ${{ github.event.inputs.version }}" 
       
