name: Deploy
on:
  workflow_call:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Download artifact from Github
      run: |
        echo "Version is: ${{ github.event.inputs.version }}" 
        wget https://nuget.pkg.github.com/2115-27/dotnetcore-hello-world/Helloworld/${{ github.event.inputs.version }}/package.nupkg
       
