name: .NET Build

on:
  workflow_dispatch:
  
jobs:
  Pre-Release:
    name: Pre-Release
    uses: 2115-27/java-maven-sample-war/.github/workflows/pre-release.yml@versntest
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  sonar:
      name: Sonar Analysis
      needs: build
      uses: ./.github/workflows/Sonar.yml
      
  upload:
    runs-on: windows-latest
    needs: [build,sonar,Pre-Release]
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to GitHub Actions
      run: dotnet nuget add source --username Malavika1113 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Malavika1113/index.json"
    - name: Pack Package
      run: dotnet pack --configuration Release --version ${{needs.Pre-Release.outputs.currentversion}}
    - name: Publish Package
      run: dotnet nuget push "bin/Release/Helloworld.${{needs.Pre-Release.outputs.currentversion}}.nupkg" --source "github"
      
      
  
