name: .NET

on:
  workflow_dispatch:
  
jobs:

  Pre-Release:
    name: Pre-Release
    uses: 2115-27/java-maven-sample-war/.github/workflows/pre-release.yml@versntest
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
  build:

    runs-on: ubuntu-latest
    needs: [Pre-Release]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
    - name: Build
      run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal

#   sonarcloud:
#      name: Sonar
#      uses: ./.github/workflows/sonar.yml
#      needs: [Pre-Release]
     
  upload:
    needs: [build,Pre-Release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to GitHub Actions
      run: dotnet nuget add source --username 2115-27 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/2115-27/index.json"
    - name: Pack Package
      run: |
       echo ${{needs.Pre-Release.outputs.currentversion}}
       dotnet pack --configuration Release -p:PackageVersion=${{needs.Pre-Release.outputs.currentversion}}
    
    - name: Publish Package
      run: |
        dotnet nuget push "bin/Release/*.nupkg" --source "github"
  deploy:
    needs: [upload]
    runs-on: ubuntu-latest
    env:
        AZURE_WEBAPP_NAME: Helloworld    
        AZURE_WEBAPP_PACKAGE_PATH: '.'     
        DOTNET_VERSION: '3.1.x'    
    steps:
      - name: Download artifact from build job
        run: dotnet add package Helloworld --version 22.2.7

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
