name: CD STAGE

on:
  workflow_dispatch:

jobs:
  
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  STG_Deploy:
   needs: pre-deploy
   uses: ./.github/workflows/stgdeploy.yml
     
  post-deploy:
    runs-on: ubuntu-latest
    needs: STG_Deploy
    steps:
     - name: Post Deployment
       run: echo Hello, world Post Deployment!
