name: CD STAGE

on:
  workflow_dispatch:

jobs:
  
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  STG_Deploy:
   needs: pre-deploy
   runs-on: ubuntu-latest
   environment: STG
   steps:
    - name: Enable workflow
      run: gh workflow enable "stgdeploy.yml" 
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
  post-deploy:
    runs-on: ubuntu-latest
    needs: STG_Deploy
    steps:
     - name: Post Deployment
       run: echo Hello, world Post Deployment!
