name: Github wiki 

on:
  workflow_dispatch:
  
jobs:
  Wiki_clone:
    name: cloneWIKI
    runs-on: ubuntu-latest
    steps:
      - name: Wiki Contents
        run: |
          git clone https://github.com/Malavika1113/dotnetcore-hello-world.wiki.git
          ls -la
          cd dotnetcore-hello-world.wiki
          ls -la
          cat Dashboard.org
          sed -i 's/\bApp1Dev*/App1Dev *version-1.2.5*/' Dashboard.org
          echo "############################"
          cat Dashboard.org
