name: Github wiki 

on:
  workflow_dispatch:
  
jobs:
  Wiki_clone:
    name: cloneWIKI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: markdown
#       - name: Wiki Contents
#         run: |
#           cd markdown
#           ls -la
#           cat Dashboard.org
#           sed -i 's/\bApp3STGVersion[^ ]*/App3STGVersion-1.2.5/' Dashboard.org
#           echo "#############################################################################"
#           cat Dashboard.org
#           echo "#############################################################################3"
#           echo "${{ runner.name }}"
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
